routes/admin.php
<?php

routes/web.php
<?php

/*搜索*/
Route::get('/posts/search', 'PostController@search')->name('search');

/* 文章模块 */
Route::resource('posts', 'PostController');
// URL跳转
/*Route::get('posts', function () {
    return redirect()->route('posts.index');
});*/
// 首页
Route::get('/', 'PostController@index')->name('posts.index');
// 文章图片上传
Route::post('posts/image/upload', 'PostController@imageUpload')->name('posts.imageUpload');
// 文章评论
Route::post('posts/{post}/comment', 'PostController@comment')->name('posts.comment');

/* 用户模块*/
// 用户注册
Route::get('register', 'RegisterController@index')->name('register.index');
Route::post('register', 'RegisterController@store')->name('register.store');
// 验证码
Route::get('register/code', 'RegisterController@code')->name('register.code');
//Route::get('register/getcode', 'RegisterController@getcode')->name('register.getcode');

// 登录
Route::get('login', 'LoginController@index')->name('login');
Route::post('login', 'LoginController@store')->name('login.store');
// 登出
Route::get('logout', 'LoginController@logout')->name('logout');


/*用户个人中心*/
// 个人设置页面
Route::get('user/me/setting', 'UserController@setting')->name('user.setting');
// 个人设置操作
Route::post('user/me/setting', 'UserController@settingStore')->name('user.settingStore');
// 个人中心
Route::get('user/{user}', 'UserController@show')->name('user.show');
// 关注与取消关注
Route::post('user/{user}/follow', 'UserController@follow')->name('user.follow');
Route::post('user/{user}/unFollow', 'UserController@unFollow')->name('user.unFollow');


/*点赞模块*/
Route::get('posts/{post}/zan', 'PostController@zan')->name('posts.zan');
Route::get('posts/{post}/unzan', 'PostController@unzan')->name('posts.unzan');


/*专题模块*/
// 专题详情页
Route::get('topic/{topic}', 'TopicController@show')->name('topic.show');
// 投稿
Route::post('topic/{topic}/submit', 'TopicController@submit')->name('topic.submit');


/* 通知模块 */
Route::get('notices', 'NoticeController@index');


/* 后台路由 */

Route::group(['prefix' => 'admin'], function () {
    // 登录页面
    Route::get('login', 'Admin\LoginController@index')->name('adminLogin.index');
    // 登录提交
    Route::post('login', 'Admin\LoginController@login')->name('adminLogin.login');
    // 登出
    Route::get('logout', 'Admin\LoginController@logout')->name('adminLogin.logout');


    // 首页
    Route::get('home', 'Admin\HomeController@index')->name('adminHome.index');

    /* 角色权限 */
    Route::group(['middleware' => 'can:system'], function () {
        // 管理人员模块
        Route::get('users', 'Admin\UserController@index')->name('adminUser.index');
        Route::get('users/create', 'Admin\UserController@create')->name('adminUser.create');
        Route::post('users/store', 'Admin\UserController@store')->name('adminUser.store');

        /* 角色模块 */
        // 角色列表页
        Route::get('roles', 'Admin\RoleController@index')->name('role.index');
        // 角色创建
        Route::get('roles/create', 'Admin\RoleController@create')->name('role.create');
        Route::post('roles/store', 'Admin\RoleController@store')->name('role.store');

        // 角色 & 用户 关联
        Route::get('users/{user}/role', 'Admin\UserController@role')->name('adminUser.role');
        Route::post('users/{user}/role', 'Admin\UserController@storeRole')->name('adminUser.storeRole');
        // 权限 & 角色 关联
        Route::get('roles/{role}/permission', 'Admin\RoleController@permission')->name('role.permission');
        Route::post('roles/{role}/permission', 'Admin\RoleController@storePermission')->name('role.storePermission');

        /* 权限模块 */
        // 权限列表页
        Route::get('permissions', 'Admin\PermissionController@index')->name('permission.index');
        // 权限创建
        Route::get('permissions/create', 'Admin\PermissionController@create')->name('permission.create');
        Route::post('permissions/store', 'Admin\PermissionController@store')->name('permission.store');
    });

    Route::group(['middleware' => 'can:post'], function () {
        // 文章管理模块
        Route::get('posts', 'Admin\PostController@index')->name('adminPost.index');
        Route::post('posts/{post}/status', 'Admin\PostController@status')->name('adminPost.status');
    });


    /* 专题模块 */
    Route::group(['middleware' => 'can:topic'], function () {
        Route::resource('topics', 'Admin\TopicController', ['only' => ['index', 'create', 'store', 'destroy']]);
    });


    /* 通知模块 */
    Route::group(['middleware' => 'can:notice'], function () {
        Route::resource('notices', 'Admin\NoticeController', ['only' => ['index', 'create', 'store']]);
    });
});

app/Models/Topic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{

    protected $fillable = ['name'];

    // 属于某个专题的所有文章    专题 & 文章 多对多
    public function posts()
    {
        return $this->belongsToMany(\App\Models\Post::class, 'post_topics', 'topic_id', 'post_id');
    }

    // 专题的文章数, 用于 withCount
    public function postTopics()
    {
        return $this->hasMany(\App\Models\PostTopic::class, 'topic_id');
    }
}

app/Http/Controllers/Admin/TopicController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Topic;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TopicController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $topics = Topic::all();

        return view('admin/topic/index', compact('topics'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/topic/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string'
        ], [
            'name.required' => '请填写专题名',
        ]);

        $result = Topic::create(['name' => $request->get('name')]);

        if (! $result) {
            return back()->withErrors('请填写内容');
        }

        return redirect()->route('topics.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic $topic)
    {
        $topic->delete();

        return [
            'error' => 0,
            'msg' => '',
        ];
    }
}

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\Models\PostTopic;
use App\Models\Topic;
use Illuminate\Http\Request;

class TopicController extends Controller
{
    public function __construct()
    {
        return $this->middleware('auth');
    }

    //  专题详情
    public function show(Topic $topic)
    {
        // 带文章数的专题
        $topic = Topic::withCount('postTopics')->find($topic->id);

        // 专题的文章列表，按照创建时间倒序排列
        $posts = $topic->posts()->orderBy('created_at', 'desc')->take(10)->get();

        // 用户未投稿文章
        $myposts = \App\Models\Post::authorBy(\Auth::id())->topicNotBy($topic->id)->get();

        return view('topic.show', compact('topic', 'posts', 'myposts'));
    }

    // 投稿
    public function submit(Topic $topic)
    {
        // 验证表单提交数据
        $this->validate(\request(), [
            'post_ids'      =>  'required|array'
        ]);

        // 逻辑
        $post_ids = \request('post_ids');
        $topic_id = $topic->id;
        foreach ($post_ids as $post_id) {
            PostTopic::firstOrCreate(compact('topic_id', 'post_id'));
        }

        return back();
    }

}

resources/views/admin/topic/create.blade.php
@extends('admin.layouts.main')

@section('content')
<!-- Main content -->
<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-lg-10 col-xs-6">
            <div class="box">

                <!-- /.box-header -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">增加专题</h3>
                    </div>

                    @include('messages.errors')
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="{{ route('topics.store') }}" method="POST">
                        {{ csrf_field() }}
                        <div class="box-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">专题名</label>
                                <input type="text" class="form-control" name="name">
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">提交</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@stop

resources/views/admin/topic/index.blade.php
@extends('admin.layouts.main')

@section('content')
<!-- Main content -->
<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-lg-10 col-xs-6">
            <div class="box">

                <div class="box-header with-border">
                    <h3 class="box-title">专题列表</h3>
                </div>
                <a type="button" class="btn " href="{{ route('topics.create') }}" >增加专题</a>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table table-bordered">
                        <tbody><tr>
                            <th style="width: 10px">#</th>
                            <th>专题名称</th>
                            <th>操作</th>
                        </tr>
                        @foreach($topics as $topic)
                        <tr>
                            <td>{{ $topic->id }}</td>
                            <td>{{ $topic->name }}</td>
                            <td>
                                <a type="button" class="btn resource-delete" delete-url="/admin/topics/{{ $topic->id }}" href="javascript:;" >删除</a>
                            </td>
                        </tr>
                        @endforeach
                        </tbody></table>
                </div>
            </div>
        </div>
    </div>
</section>
@stop