routes/admin.php
<?php

routes/web.php
<?php

/*搜索*/
Route::get('/posts/search', 'PostController@search')->name('search');

/* 文章模块 */
Route::resource('posts', 'PostController');
// URL跳转
/*Route::get('posts', function () {
    return redirect()->route('posts.index');
});*/
// 首页
Route::get('/', 'PostController@index')->name('posts.index');
// 文章图片上传
Route::post('posts/image/upload', 'PostController@imageUpload')->name('posts.imageUpload');
// 文章评论
Route::post('posts/{post}/comment', 'PostController@comment')->name('posts.comment');

/* 用户模块*/
// 用户注册
Route::get('register', 'RegisterController@index')->name('register.index');
Route::post('register', 'RegisterController@store')->name('register.store');
// 验证码
Route::get('register/code', 'RegisterController@code')->name('register.code');
//Route::get('register/getcode', 'RegisterController@getcode')->name('register.getcode');

// 登录
Route::get('login', 'LoginController@index')->name('login');
Route::post('login', 'LoginController@store')->name('login.store');
// 登出
Route::get('logout', 'LoginController@logout')->name('logout');


/*用户个人中心*/
// 个人设置页面
Route::get('user/me/setting', 'UserController@setting')->name('user.setting');
// 个人设置操作
Route::post('user/me/setting', 'UserController@settingStore')->name('user.settingStore');
// 个人中心
Route::get('user/{user}', 'UserController@show')->name('user.show');
// 关注与取消关注
Route::post('user/{user}/follow', 'UserController@follow')->name('user.follow');
Route::post('user/{user}/unFollow', 'UserController@unFollow')->name('user.unFollow');


/*点赞模块*/
Route::get('posts/{post}/zan', 'PostController@zan')->name('posts.zan');
Route::get('posts/{post}/unzan', 'PostController@unzan')->name('posts.unzan');


/*专题模块*/
// 专题详情页
Route::get('topic/{topic}', 'TopicController@show')->name('topic.show');
// 投稿
Route::post('topic/{topic}/submit', 'TopicController@submit')->name('topic.submit');


/* 通知模块 */
Route::get('notices', 'NoticeController@index');


/* 后台路由 */

Route::group(['prefix' => 'admin'], function () {
    // 登录页面
    Route::get('login', 'Admin\LoginController@index')->name('adminLogin.index');
    // 登录提交
    Route::post('login', 'Admin\LoginController@login')->name('adminLogin.login');
    // 登出
    Route::get('logout', 'Admin\LoginController@logout')->name('adminLogin.logout');


    // 首页
    Route::get('home', 'Admin\HomeController@index')->name('adminHome.index');

    /* 角色权限 */
    Route::group(['middleware' => 'can:system'], function () {
        // 管理人员模块
        Route::get('users', 'Admin\UserController@index')->name('adminUser.index');
        Route::get('users/create', 'Admin\UserController@create')->name('adminUser.create');
        Route::post('users/store', 'Admin\UserController@store')->name('adminUser.store');

        /* 角色模块 */
        // 角色列表页
        Route::get('roles', 'Admin\RoleController@index')->name('role.index');
        // 角色创建
        Route::get('roles/create', 'Admin\RoleController@create')->name('role.create');
        Route::post('roles/store', 'Admin\RoleController@store')->name('role.store');

        // 角色 & 用户 关联
        Route::get('users/{user}/role', 'Admin\UserController@role')->name('adminUser.role');
        Route::post('users/{user}/role', 'Admin\UserController@storeRole')->name('adminUser.storeRole');
        // 权限 & 角色 关联
        Route::get('roles/{role}/permission', 'Admin\RoleController@permission')->name('role.permission');
        Route::post('roles/{role}/permission', 'Admin\RoleController@storePermission')->name('role.storePermission');

        /* 权限模块 */
        // 权限列表页
        Route::get('permissions', 'Admin\PermissionController@index')->name('permission.index');
        // 权限创建
        Route::get('permissions/create', 'Admin\PermissionController@create')->name('permission.create');
        Route::post('permissions/store', 'Admin\PermissionController@store')->name('permission.store');
    });

    Route::group(['middleware' => 'can:post'], function () {
        // 文章管理模块
        Route::get('posts', 'Admin\PostController@index')->name('adminPost.index');
        Route::post('posts/{post}/status', 'Admin\PostController@status')->name('adminPost.status');
    });


    /* 专题模块 */
    Route::group(['middleware' => 'can:topic'], function () {
        Route::resource('topics', 'Admin\TopicController', ['only' => ['index', 'create', 'store', 'destroy']]);
    });


    /* 通知模块 */
    Route::group(['middleware' => 'can:notice'], function () {
        Route::resource('notices', 'Admin\NoticeController', ['only' => ['index', 'create', 'store']]);
    });
});

app/Models/Notice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Notice extends Model
{
    protected $fillable = ['title', 'content'];
}

app/Http/Controllers/Admin/NoticeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Jobs\SendMessage;
use App\Models\Notice;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class NoticeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * 通知列表
     *
     * @return
     */
    public function index()
    {
        $notices = Notice::all();
        return view('admin/notice/index', compact('notices'));
    }

    /**
     * 创建通知
     *
     * @return
     */
    public function create()
    {
        return view('admin/notice/create');
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|string',
            'content' => 'required|string'
        ]);

        $notice = Notice::create($request->all(['title', 'content']));

        // 分发通知
        dispatch(new SendMessage($notice));

        return redirect()->route('notices.index');
    }
}

app/Http/Controllers/NoticeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class NoticeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        // 当前用户收到的 notices
        $user = \Auth::user();  // 获取当前用户

        $notices = $user->notices;  // 已定义了模型关联，使用非函数的形式获取对象

        return view('notice/index', compact('notices'));
    }
}

resources/views/admin/notice/create.blade.php
@extends('admin.layouts.main')

@section('content')
<section class="content">
    <div class="row">
        <div class="col-lg-10 col-xs-6">
            <div class="box">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">增加通知</h3>
                    </div>
                    <form role="form" action="{{ route('notices.store') }}" method="POST">
                        {{ csrf_field() }}
                        <div class="box-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">标题</label>
                                <input type="text" class="form-control" name="title">
                            </div>
                        </div>
                        <div class="box-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">内容</label>
                                <textarea class="form-control" name="content"></textarea>
                            </div>
                        </div>
                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">提交</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@stop

resources/views/admin/notice/index.blade.php
@extends('admin.layouts.main')

@section('content')
<!-- Main content -->
<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-lg-10 col-xs-6">
            <div class="box">

                <div class="box-header with-border">
                    <h3 class="box-title">通知列表</h3>
                </div>
                <a type="button" class="btn " href="{{ route('notices.create') }}">增加通知</a>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table table-bordered">
                        <tbody><tr>
                            <th style="width: 10px">#</th>
                            <th>通知名称</th>
                            <th>操作</th>
                        </tr>
                        @foreach($notices as $notice)
                        <tr>
                            <td>{{ $notice->id }}</td>
                            <td>{{ $notice->title }}</td>
                            <td></td>
                        </tr>
                        @endforeach
                        </tbody></table>
                </div>
            </div>
        </div>
    </div>
</section>
@stop