routes/admin.php
<?php

routes/web.php
<?php

/*搜索*/
Route::get('/posts/search', 'PostController@search')->name('search');

/* 文章模块 */
Route::resource('posts', 'PostController');
// URL跳转
/*Route::get('posts', function () {
    return redirect()->route('posts.index');
});*/
// 首页
Route::get('/', 'PostController@index')->name('posts.index');
// 文章图片上传
Route::post('posts/image/upload', 'PostController@imageUpload')->name('posts.imageUpload');
// 文章评论
Route::post('posts/{post}/comment', 'PostController@comment')->name('posts.comment');

/* 用户模块*/
// 用户注册
Route::get('register', 'RegisterController@index')->name('register.index');
Route::post('register', 'RegisterController@store')->name('register.store');
// 验证码
Route::get('register/code', 'RegisterController@code')->name('register.code');
//Route::get('register/getcode', 'RegisterController@getcode')->name('register.getcode');

// 登录
Route::get('login', 'LoginController@index')->name('login');
Route::post('login', 'LoginController@store')->name('login.store');
// 登出
Route::get('logout', 'LoginController@logout')->name('logout');


/*用户个人中心*/
// 个人设置页面
Route::get('user/me/setting', 'UserController@setting')->name('user.setting');
// 个人设置操作
Route::post('user/me/setting', 'UserController@settingStore')->name('user.settingStore');
// 个人中心
Route::get('user/{user}', 'UserController@show')->name('user.show');
// 关注与取消关注
Route::post('user/{user}/follow', 'UserController@follow')->name('user.follow');
Route::post('user/{user}/unFollow', 'UserController@unFollow')->name('user.unFollow');


/*点赞模块*/
Route::get('posts/{post}/zan', 'PostController@zan')->name('posts.zan');
Route::get('posts/{post}/unzan', 'PostController@unzan')->name('posts.unzan');


/*专题模块*/
// 专题详情页
Route::get('topic/{topic}', 'TopicController@show')->name('topic.show');
// 投稿
Route::post('topic/{topic}/submit', 'TopicController@submit')->name('topic.submit');


/* 通知模块 */
Route::get('notices', 'NoticeController@index');


/* 后台路由 */

Route::group(['prefix' => 'admin'], function () {
    // 登录页面
    Route::get('login', 'Admin\LoginController@index')->name('adminLogin.index');
    // 登录提交
    Route::post('login', 'Admin\LoginController@login')->name('adminLogin.login');
    // 登出
    Route::get('logout', 'Admin\LoginController@logout')->name('adminLogin.logout');


    // 首页
    Route::get('home', 'Admin\HomeController@index')->name('adminHome.index');

    /* 角色权限 */
    Route::group(['middleware' => 'can:system'], function () {
        // 管理人员模块
        Route::get('users', 'Admin\UserController@index')->name('adminUser.index');
        Route::get('users/create', 'Admin\UserController@create')->name('adminUser.create');
        Route::post('users/store', 'Admin\UserController@store')->name('adminUser.store');

        /* 角色模块 */
        // 角色列表页
        Route::get('roles', 'Admin\RoleController@index')->name('role.index');
        // 角色创建
        Route::get('roles/create', 'Admin\RoleController@create')->name('role.create');
        Route::post('roles/store', 'Admin\RoleController@store')->name('role.store');

        // 角色 & 用户 关联
        Route::get('users/{user}/role', 'Admin\UserController@role')->name('adminUser.role');
        Route::post('users/{user}/role', 'Admin\UserController@storeRole')->name('adminUser.storeRole');
        // 权限 & 角色 关联
        Route::get('roles/{role}/permission', 'Admin\RoleController@permission')->name('role.permission');
        Route::post('roles/{role}/permission', 'Admin\RoleController@storePermission')->name('role.storePermission');

        /* 权限模块 */
        // 权限列表页
        Route::get('permissions', 'Admin\PermissionController@index')->name('permission.index');
        // 权限创建
        Route::get('permissions/create', 'Admin\PermissionController@create')->name('permission.create');
        Route::post('permissions/store', 'Admin\PermissionController@store')->name('permission.store');
    });

    Route::group(['middleware' => 'can:post'], function () {
        // 文章管理模块
        Route::get('posts', 'Admin\PostController@index')->name('adminPost.index');
        Route::post('posts/{post}/status', 'Admin\PostController@status')->name('adminPost.status');
    });


    /* 专题模块 */
    Route::group(['middleware' => 'can:topic'], function () {
        Route::resource('topics', 'Admin\TopicController', ['only' => ['index', 'create', 'store', 'destroy']]);
    });


    /* 通知模块 */
    Route::group(['middleware' => 'can:notice'], function () {
        Route::resource('notices', 'Admin\NoticeController', ['only' => ['index', 'create', 'store']]);
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    // 用户的文章列表
    public function posts()
    {
        return $this->hasMany(\App\Models\Post::class, 'user_id', 'id');
    }

    // 我的粉丝
    public function fans()
    {
        return $this->hasMany(\App\Models\Fan::class, 'star_id', 'id');
    }

    // 关注用户列表
    public function followers()
    {
        return $this->hasMany(\App\Models\Fan::class, 'fan_id', 'id');
    }

    // 我关注某人
    public function follow($uid)
    {
        $fan = new Fan();
        $fan->star_id = $uid;
        return $this->followers()->save($fan);
    }

    // 取消关注
    public function unFollow($uid)
    {
        $fan = new Fan();
        $fan->star_id = $uid;
        return $this->followers()->delete($fan);
    }

    // 当前用户是否被uid关注了
    public function beFollowed($uid)
    {
        return $this->fans()->where('fan_id', $uid)->count();
    }

    // 当前用户是否关注了uid
    public function isFollowing($uid)
    {
        return $this->followers()->where('star_id', $uid)->count();
    }

    // 用户收到的通知, 多对多关联
    public function notices()
    {
        return $this->belongsToMany(\App\Models\Notice::class, 'user_notice', 'user_id', 'notice_id')->withPivot(['user_id', 'notice_id']);
    }

    // 给用户增加通知
    public function addNotice($notice)
    {
        return $this->notices()->save($notice);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\AdminUser;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    // 管理员列表
    public function index()
    {
        $users = AdminUser::paginate(10);
        return view('admin.user.index', compact('users'));
    }

    // 添加管理员页面
    public function create()
    {
        return view('admin.user.add');
    }

    // 添加管理员
    public function store(Request $request)
    {
        // 验证数据
        $this->validate($request, [
            'name' => 'required|min:2|max:20',
            'email' => 'required|email',
            'password' => 'required|min:6',
        ]);

        // 逻辑
        $name = $request->get('name');
        $email = $request->get('email');
        $password = bcrypt($request->get('password'));
        AdminUser::create(compact('name', 'email', 'password'));

        return redirect()->route('adminUser.index');
    }

    // 用户角色页面
    public function role(AdminUser $user)
    {
        $roles = \App\Models\AdminRole::all();  // 所有角色
        $myRoles = $user->roles;

        return view('admin/user/role', compact('roles', 'myRoles', 'user'));
    }

    //
    public function storeRole(AdminUser $user)
    {
        $this->validate(\request(), [
            'roles' => 'required|array'
        ]);

        $roles = \App\Models\AdminRole::findMany(\request('roles'));
        $myRoles = $user->roles;

        // 要增加的
        $addRoles = $roles->diff($myRoles);
        foreach ($addRoles as $role) {
            $user->assignRole($role);
        }

        // 要删除的
        $deleteRoles = $myRoles->diff($roles);
        foreach ($deleteRoles as $role) {
            $user->deleteRole($role);
        }

        return back();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ImageUploadRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    // 用户个人设置页面
    public function setting()
    {
        return view('user.setting');
    }

    /**
     * 用户个人设置表单提交处理
     *
     * @param Request $request
     * @return $this|\Illuminate\Http\RedirectResponse|string
     */
    public function settingStore(Request $request)
    {
        // 验证
        $this->validate($request, [
            'name'      =>  'required|min:2',
            'avatar'    =>  'image|dimensions:max_width=800,max_height=600',
        ],[
            'avatar.dimensions' =>  '图片的尺寸不能超过 800 * 600 像素'
        ]);

        // 逻辑
        $name = $request->get('name');
        $user = \Auth::user();
        if ($name != $user->name) {     // 判断用户名是否有更改
            if (User::where('name', $name)->count() > 0) {  // 判断用户名是否已存在
                return back()->withErrors('用户名已经被注册');
            }
            $user->name = $name;
        }

        if ($request->file('avatar')) {     // 判断是否有上传头像图片
            $path = Storage::putFile('avatar/' . date('Ym', time()) . '/' . date('d', time()), $request->file('avatar'));
            $user->avatar = "/storage/" . $path;
        }

        $user->save();

        session()->flash('success', '更新用户资料成功');

        return back();
    }

    // 个人中心
    public function show(User $user)
    {
        // 向视图传递个人信息，包括：关注 / 粉丝 / 文章数
        $user = User::withCount(['fans', 'followers', 'posts'])->find($user->id);  // User.php 中定义的模型关联

        // 文章列表，取创建时间最新的前 10 条
        $posts = $user->posts()->orderBy('created_at', 'desc')->take(10)->get();

        // 关注的用户，包括关注用户的 关注 / 粉丝 / 文章数
        $followers = $user->followers;
        $starUsers = User::whereIn('id', $followers->pluck('star_id'))
                        ->withCount(['followers', 'fans', 'posts'])
                        ->get();

        // 粉丝用户，包含粉丝用户的 关注 / 粉丝 / 文章数
        $fans = $user->fans;
        $fanUsers = User::whereIn('id', $fans->pluck('fan_id'))
                        ->withCount(['followers', 'fans', 'posts'])
                        ->get();

        return view('user.show', compact('user', 'posts', 'starUsers', 'fanUsers'));
    }

    // 关注用户
    public function follow(User $user)
    {
        $me = \Auth::user();    // 当前用户
        $me->follow($user->id);  // 关注用户

        return [
            'error'     =>  0,
            'message'   =>  ''
        ];
    }

    // 取消关注
    public function unFollow(User $user)
    {
        $me = \Auth::user();        // 当前用户
        $me->unFollow($user->id);    // 取消关注
        return [
            'error'     =>  0,
            'message'   =>  ''
        ];
    }
}

resources/views/user/setting.blade.php
@extends('layouts.main')

@section('content')
    <div class="col-sm-8 blog-main">
        @include('messages.message')
        <form class="form-horizontal" action="{{ route('user.settingStore') }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="form-group">
                <label class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    <input class="form-control" name="name" type="text" value="{{ Auth::user()->name }}">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">头像</label>
                <div class="col-sm-2">
                    <input class="file-loading preview_input" type="file" value=""  name="avatar" style="margin-top: 5px;">
                    <img  class="preview_img" src="{{ Auth::user()->avatar }}" alt="" class="img-rounded" style="width: 200px; height:200px;border-radius: 100%; margin-top: 20px;">
                </div>
            </div>
            @include('messages.errors')
            <button type="submit" class="btn btn-default" style="margin-left: 20px;">修改</button>
        </form>
        <br>

    </div>
@stop

resources/views/user/show.blade.php
@extends('layouts.main')

@section('content')
<div class="col-sm-8">
    <blockquote>
        <p><img src="{{ $user->avatar }}" alt="" class="img-rounded" style="border-radius:100%; width: 60px; height: 60px"> {{ $user->name }}
        </p>
        <footer>关注：{{ $user->followers_count }}｜粉丝：{{ $user->fans_count }}｜文章：{{ $user->posts_count }}</footer>
        @include('user.badges.like', ['target_user' => $user])
    </blockquote>
</div>
<div class="col-sm-8 blog-main">
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">文章</a></li>
            <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false">关注</a></li>
            <li class=""><a href="#tab_3" data-toggle="tab" aria-expanded="false">粉丝</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab_1">
                @foreach($posts as $post)
                    <div class="blog-post" style="margin-top: 30px">
                        <p class="">
                            <a href="/user/{{ $post->user->id }}">{{ $post->user->name }}</a>
                            {{ $post->created_at }}
                        </p>
                        <p class="">
                            <a href="{{ route('posts.show', $post->id) }}" >{{ $post->title }}</a>
                        </p>
                        @if(strlen(\Illuminate\Support\Str::words($post->content, 1)) > 102)
                            {!! str_limit($post->content, 102, '......') !!}
                        @else
                            {!! \Illuminate\Support\Str::words($post->content, 1) !!}
                        @endif
                    </div>
                @endforeach
            </div>
            <!-- /.tab-pane -->
            <div class="tab-pane" id="tab_2">
                @foreach($starUsers as $user)
                    <div class="blog-post" style="margin-top: 30px">
                    <p class="">
                        <a href="{{ route('user.show', $user->id) }}">{{ $user->name }}</a>
                    </p>
                    <p class="">关注：{{ $user->followers_count }} | 粉丝：{{ $user->fans_count }}｜ 文章：{{ $user->posts_count }}</p>
                    @include('user.badges.like', ['target_user' => $user])
                </div>
                @endforeach
            </div>
            <!-- /.tab-pane -->
            <div class="tab-pane" id="tab_3">
                @foreach($fanUsers as $user)
                    <div class="blog-post" style="margin-top: 30px">
                        <p class="">
                            <a href="{{ route('user.show',$user->id) }}">{{ $user->name }}</a>
                        </p>
                        <p class="">关注：{{ $user->follwers_count }} | 粉丝：{{ $user->fans_count }}｜ 文章：{{ $user->posts_count }}</p>
                    @include('user.badges.like', ['target_user' => $user])
                    </div>
                @endforeach
            </div>
            <!-- /.tab-pane -->
        </div>
        <!-- /.tab-content -->
    </div>
</div>
@stop