routes/admin.php
<?php

routes/web.php
<?php

/*搜索*/
Route::get('/posts/search', 'PostController@search')->name('search');

/* 文章模块 */
Route::resource('posts', 'PostController');
// URL跳转
/*Route::get('posts', function () {
    return redirect()->route('posts.index');
});*/
// 首页
Route::get('/', 'PostController@index')->name('posts.index');
// 文章图片上传
Route::post('posts/image/upload', 'PostController@imageUpload')->name('posts.imageUpload');
// 文章评论
Route::post('posts/{post}/comment', 'PostController@comment')->name('posts.comment');

/* 用户模块*/
// 用户注册
Route::get('register', 'RegisterController@index')->name('register.index');
Route::post('register', 'RegisterController@store')->name('register.store');
// 验证码
Route::get('register/code', 'RegisterController@code')->name('register.code');
//Route::get('register/getcode', 'RegisterController@getcode')->name('register.getcode');

// 登录
Route::get('login', 'LoginController@index')->name('login');
Route::post('login', 'LoginController@store')->name('login.store');
// 登出
Route::get('logout', 'LoginController@logout')->name('logout');


/*用户个人中心*/
// 个人设置页面
Route::get('user/me/setting', 'UserController@setting')->name('user.setting');
// 个人设置操作
Route::post('user/me/setting', 'UserController@settingStore')->name('user.settingStore');
// 个人中心
Route::get('user/{user}', 'UserController@show')->name('user.show');
// 关注与取消关注
Route::post('user/{user}/follow', 'UserController@follow')->name('user.follow');
Route::post('user/{user}/unFollow', 'UserController@unFollow')->name('user.unFollow');


/*点赞模块*/
Route::get('posts/{post}/zan', 'PostController@zan')->name('posts.zan');
Route::get('posts/{post}/unzan', 'PostController@unzan')->name('posts.unzan');


/*专题模块*/
// 专题详情页
Route::get('topic/{topic}', 'TopicController@show')->name('topic.show');
// 投稿
Route::post('topic/{topic}/submit', 'TopicController@submit')->name('topic.submit');


/* 通知模块 */
Route::get('notices', 'NoticeController@index');


/* 后台路由 */

Route::group(['prefix' => 'admin'], function () {
    // 登录页面
    Route::get('login', 'Admin\LoginController@index')->name('adminLogin.index');
    // 登录提交
    Route::post('login', 'Admin\LoginController@login')->name('adminLogin.login');
    // 登出
    Route::get('logout', 'Admin\LoginController@logout')->name('adminLogin.logout');


    // 首页
    Route::get('home', 'Admin\HomeController@index')->name('adminHome.index');

    /* 角色权限 */
    Route::group(['middleware' => 'can:system'], function () {
        // 管理人员模块
        Route::get('users', 'Admin\UserController@index')->name('adminUser.index');
        Route::get('users/create', 'Admin\UserController@create')->name('adminUser.create');
        Route::post('users/store', 'Admin\UserController@store')->name('adminUser.store');

        /* 角色模块 */
        // 角色列表页
        Route::get('roles', 'Admin\RoleController@index')->name('role.index');
        // 角色创建
        Route::get('roles/create', 'Admin\RoleController@create')->name('role.create');
        Route::post('roles/store', 'Admin\RoleController@store')->name('role.store');

        // 角色 & 用户 关联
        Route::get('users/{user}/role', 'Admin\UserController@role')->name('adminUser.role');
        Route::post('users/{user}/role', 'Admin\UserController@storeRole')->name('adminUser.storeRole');
        // 权限 & 角色 关联
        Route::get('roles/{role}/permission', 'Admin\RoleController@permission')->name('role.permission');
        Route::post('roles/{role}/permission', 'Admin\RoleController@storePermission')->name('role.storePermission');

        /* 权限模块 */
        // 权限列表页
        Route::get('permissions', 'Admin\PermissionController@index')->name('permission.index');
        // 权限创建
        Route::get('permissions/create', 'Admin\PermissionController@create')->name('permission.create');
        Route::post('permissions/store', 'Admin\PermissionController@store')->name('permission.store');
    });

    Route::group(['middleware' => 'can:post'], function () {
        // 文章管理模块
        Route::get('posts', 'Admin\PostController@index')->name('adminPost.index');
        Route::post('posts/{post}/status', 'Admin\PostController@status')->name('adminPost.status');
    });


    /* 专题模块 */
    Route::group(['middleware' => 'can:topic'], function () {
        Route::resource('topics', 'Admin\TopicController', ['only' => ['index', 'create', 'store', 'destroy']]);
    });


    /* 通知模块 */
    Route::group(['middleware' => 'can:notice'], function () {
        Route::resource('notices', 'Admin\NoticeController', ['only' => ['index', 'create', 'store']]);
    });
});

app/Models/Topic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{

    protected $fillable = ['name'];

    // 属于某个专题的所有文章    专题 & 文章 多对多
    public function posts()
    {
        return $this->belongsToMany(\App\Models\Post::class, 'post_topics', 'topic_id', 'post_id');
    }

    // 专题的文章数, 用于 withCount
    public function postTopics()
    {
        return $this->hasMany(\App\Models\PostTopic::class, 'topic_id');
    }
}

app/Http/Controllers/Admin/TopicController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Topic;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TopicController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $topics = Topic::all();

        return view('admin/topic/index', compact('topics'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/topic/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string'
        ], [
            'name.required' => '请填写专题名',
        ]);

        $result = Topic::create(['name' => $request->get('name')]);

        if (! $result) {
            return back()->withErrors('请填写内容');
        }

        return redirect()->route('topics.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic $topic)
    {
        $topic->delete();

        return [
            'error' => 0,
            'msg' => '',
        ];
    }
}

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\Models\PostTopic;
use App\Models\Topic;
use Illuminate\Http\Request;

class TopicController extends Controller
{
    public function __construct()
    {
        return $this->middleware('auth');
    }

    //  专题详情
    public function show(Topic $topic)
    {
        // 带文章数的专题
        $topic = Topic::withCount('postTopics')->find($topic->id);

        // 专题的文章列表，按照创建时间倒序排列
        $posts = $topic->posts()->orderBy('created_at', 'desc')->take(10)->get();

        // 用户未投稿文章
        $myposts = \App\Models\Post::authorBy(\Auth::id())->topicNotBy($topic->id)->get();

        return view('topic.show', compact('topic', 'posts', 'myposts'));
    }

    // 投稿
    public function submit(Topic $topic)
    {
        // 验证表单提交数据
        $this->validate(\request(), [
            'post_ids'      =>  'required|array'
        ]);

        // 逻辑
        $post_ids = \request('post_ids');
        $topic_id = $topic->id;
        foreach ($post_ids as $post_id) {
            PostTopic::firstOrCreate(compact('topic_id', 'post_id'));
        }

        return back();
    }

}

resources/views/topic/show.blade.php
@extends('layouts.main')

@section('content')
<div class="col-sm-8">
    <blockquote>
        <p>{{ $topic->name }}</p>
        <footer>文章：{{ $topic->post_topics_count }}</footer>
        <button class="btn btn-default topic-submit"  data-toggle="modal" data-target="#topic_submit_modal" topic-id="{{ $topic->id }}" _token="MESUY3topeHgvFqsy9EcM916UWQq6khiGHM91wHy" type="button">投稿</button>
    </blockquote>
</div>
<div class="modal fade" id="topic_submit_modal" tabindex="-1" role="dialog" >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">我的文章</h4>
            </div>
            <div class="modal-body">
                <form action="/topic/{{ $topic->id }}/submit" method="POST">
                    {{ csrf_field() }}
                    @foreach($myposts as $post)
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="post_ids[]" value="{{ $post->id }}">
                                {{ $post->title }}
                            </label>
                        </div>
                    @endforeach
                    <button type="submit" class="btn btn-default">投稿</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-8 blog-main">
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">文章</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab_1">
                @foreach($posts as $post)
                <div class="blog-post" style="margin-top: 30px">
                    <p class=""><a href="{{ route('user.show', $post->user->id) }}">{{ $post->user->name }}</a> {{ $post->created_at }}</p>
                    <p class=""><a href="{{ route('posts.show', $post->id) }}" >{{ $post->title }}</a></p>
                    @if(strlen(\Illuminate\Support\Str::words($post->content, 1)) > 102)
                        {!! str_limit($post->content, 102, '......') !!}
                    @else
                        {!! \Illuminate\Support\Str::words($post->content, 1) !!}
                    @endif
                </div>
                @endforeach
            </div>

        </div>
        <!-- /.tab-content -->
    </div>
</div><!-- /.blog-main -->
@stop